### ISSUE TITLE
Inquiry Regarding Sun Irradiance Values Returned by API

### ISSUE THREAD

**Issue by sPeziaLLe** [FL550/simple_dwd_weatherforecast#11]
I hope this message finds you well. I am reaching out to seek further clarification regarding the sun irradiance values I have received from your API. I have been analyzing the data for different German cities, and the irradiance values I retrieved are considerably higher than I initially anticipated.

While I am not an expert in meteorology, I had understood that the maximum possible amount of solar irradiance reaching the Earth's atmosphere is approximately 1365 W/m². Particularly in Germany, I assumed this value to be somewhat lower. However, upon examining the hourly dataframes for cities like Germany and Potsdam, I noticed that the values exceed 2000 W/m².

I must admit that I am a bit perplexed by these readings and would greatly appreciate your guidance in understanding this matter better. I would like to comprehend the specifics of the "sun_irradiance" parameter better, as it appears that my current understanding might be incomplete or incorrect. Your insights into the nature of these irradiance values and the factors that could contribute to such measurements would be invaluable.

I want to express my gratitude for the functionality of your API, which has been performing remarkably well for my purposes. I eagerly await your response and am thankful for any assistance you can provide in shedding light on this situation.

Thank you for your time and support.

Best regards
Max

**Comment by FL550** [comment]
Hi Max,

thanks for reaching out! We discussed this already in a thread for [dwd_weather for Homeassistant](https://github.com/FL550/dwd_weather/issues/65).This package here exists mainly for this integration.

The reason seems to be an error in the documentation which states the values are in Watt/m2 but actually they are in kJ/m2. I hope this helps and I should update the documentation for this.

Best regards,

Max
